[package]
name = "telegram-birthday-reminder-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
teloxide = { version = "0.13", features = ["macros"] }
pretty_env_logger = "0.5"
log = "0.4"
